### ISSUE TITLE
about output file tmp.avi and tmp.mp4

### ISSUE THREAD

**Issue by chikiuso** [Sxjdwang/TalkLip#1]
Good morning,

  It is a good project, I just have a try, it run the following command : 

python3  inf_demo.py --video_path ./input.mp4 --wav_path ./voice.wav --ckpt_path ./global_contrastive.pth --avhubert_root ./avhubert

  It run without error , but the output file tmp.avi is just 21Kb and could not play properly, and the tmp.mp4 is 0 kb, may I have your suggestion what wrong I did? or I missed something? thanks.

**Comment by Sxjdwang** [comment]
You can remove '-loglevel quiet' in the 434-th line of inf_demo.py and re-run it for details of the error.

**Comment by chikiuso** [comment]
Hi @Sxjdwang , thanks for your suggestion, I just remove the '-loglevel quiet', it seems the line is used to turn tmp.avi into mp4, it failed to convert as the input codec is unrecognizable and I found that the tmp.avi is still a few Kb file and could not be played , do I missed somthing? 

About the AVhubert, I haven't put any checkpoint or model under its folder, is it ok? or I should put some checkpoint there? thanks.

**Comment by Sxjdwang** [comment]
For inf_test and inf_demo, no av-hubert checkpoint is required. 

I find a bug in inf_demo.py that I suppose the width and height of output videos are the same when I set cv2.VideoWriter(). I have fixed it. You may try it again.

**Comment by chikiuso** [comment]
thanks a lot, it work fine!
