### ISSUE TITLE
checkpoint

### ISSUE THREAD

**Issue by Inferencer** [Sxjdwang/TalkLip#11]
sorry i'm slightly confused by the wording of the document just to be clear no pre-trained checkpoint is avaliable correct?

**Comment by Sxjdwang** [comment]
May I ask which sentences make you confused?  
![image](https://github.com/Sxjdwang/TalkLip/assets/37468393/78b916e5-c8f5-4b34-b04a-0f1cb693b581) are pre-trained checkpoints.

**Comment by Inferencer** [comment]
> 

it's becuase the inference asks for a cpkt path `--ckpt_path $talklip_ckpt` which I am now realising stands for checkpoint and not a file with an extention of .ckpt, I was up late last night apreciate the quick response & work.
