### ISSUE TITLE
Runtime error with long videos >30s

### ISSUE THREAD

**Issue by crankyz** [Sxjdwang/TalkLip#20]
With short one everything is ok, but more than ~20s got an error:
Video - 480x840 30fps Windows 11, 1080ti
RuntimeError: CUDA out of memory. Tried to allocate 3.29 GiB (GPU 0; 11.00 GiB total capacity; 7.10 GiB already allocated; 1.09 GiB free; 8.36 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.

**Comment by Sxjdwang** [comment]
The issue you've described appears to be vague. Please provide the file in which the error occurs and the full traceback. If you're referring to the 'inf_demo.py' file, you may find relevant information in the discussion thread Sxjdwang/TalkLip#13."

**Comment by crankyz** [comment]
Thank for answer, solution in #13 helped.
