### ISSUE TITLE
Calculating WER using AV_hubert

### ISSUE THREAD

**Issue by sharath-08** [Sxjdwang/TalkLip#32]
Hi,
I am trying to calculate your model's WER performance on VoxCeleb2 using your provided AV_Hubert evaluation scripts. However, I do not understand what the '../datalist/test_partial.tsv' file in toavhform.py refers to. 

Is 'datalist/' a directory in LRS2? 
If so, can you please tell me what the expected output should be from toavhform.py so I can write it for voxceleb?

Also, I'm assuming ground truth will have to be provided from us to calculate WER?

**Comment by Sxjdwang** [comment]
datalist is a directory under Talklip. You can find Talklip/datalist/test_partial.tsv.     

Yes. You need to provide ground truth as the format in  Talklip/datalist/test.wrd.

**Comment by sharath-08** [comment]
Thanks
