### ISSUE TITLE
Task state has no factory for attribute target_dictionary

### ISSUE THREAD

**Issue by Yangxiaoda1** [Sxjdwang/TalkLip#39]
My avhubert can run without any problem, but when I use the fairseq in it to execute the total train, it will report an error: AttributeError: Task state has no factory for attribute target_dictionary, may I ask which version of fairseq you are using?My fairseq version is 1.0.0a0+afc77bd

**Comment by Sxjdwang** [comment]
I use 1.0.0a0+afc77bd as well. You can provide a more detailed trackback. Maybe I can help you.

**Comment by Yangxiaoda1** [comment]
Thank you very much for your reply, I've solved the problem just now

**Comment by Sxjdwang** [comment]
Congratulations!
